--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RUISMINEX/CloudCoinsAPI
branches:
- master
projects:
  CloudCoinsAPI:
    path: ""
    libs:
      - src: CC/main
        version: 1.0.0
...
